export const ADD_WORKER_TO_SHIFTS = 'ADD_WORKER_TO_SHIFTS';
export const DEL_WORKER_TO_SHIFTS = 'DEL_WORKER_TO_SHIFTS';
export const NEXT_DAY = 'NEXT_DAY';
export const PREVIOUS_DAY = 'PREVIOUS_DAY';
export const DEL_WORKER_TO_SHIFT = 'DEL_WORKER_TO_SHIFT';
